denyinterfaces br0 eth0 eth1 lan1 lan2 lan3 lan4 lan5 lan6 lan7 lan8 sit0 ip6tnl0 lo
allowinterfaces eth2 eth3
duid
noipv4ll
releaseonexit
option domain_name_servers, domain_name, domain_search
option static_routes, classless_static_routes
option interface_mtu
option host_name
require dhcp_server_identifier
vendorclassid
slaac private
reboot 5
retry 10
