denyinterfaces br0 eth0 sit0 ip6tnl0 lo
allowinterfaces eth1
duid
noipv4ll
releaseonexit
option domain_name_servers, domain_name, domain_search
option static_routes, classless_static_routes
option interface_mtu
option host_name
require dhcp_server_identifier
vendorclassid
slaac private
reboot 5
retry 10
