#!/bin/sh

/bin/busybox mkdir -p \
        "$ROOT"/bin \
        "$ROOT"/sbin \
        "$ROOT"/usr/bin \
        "$ROOT"/usr/sbin \
        "$ROOT"/proc \
        "$ROOT"/sys \
        "$ROOT"/dev \
        "$ROOT"/media/cdrom \
        "$ROOT"/media/usb \
        "$ROOT"/tmp \
        "$ROOT"/etc \
        "$ROOT"/run/cryptsetup

/bin/busybox --install -s
export PATH="$PATH:/usr/bin:/bin:/usr/sbin:/sbin"

[ -c /dev/null ] || $MOCK mknod -m 666 /dev/null c 1 3

$MOCK mount -t tmpfs -o nosuid,nodev,noexec,size=15G,mode=1777 tmpfs /tmp
$MOCK mount -t sysfs -o noexec,nosuid,nodev sysfs /sys
$MOCK mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev

[ -c /dev/kmsg ] || $MOCK mknod -m 660 /dev/kmsg c 1 11

$MOCK mount -t proc -o noexec,nosuid,nodev proc /proc
[ -c /dev/ptmx ] || $MOCK mknod -m 666 /dev/ptmx c 5 2
[ -d /dev/pts ] || $MOCK mkdir -m 755 /dev/pts
$MOCK mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts

mkdir -p "$ROOT"/dev/shm
$MOCK mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm

[ -c /dev/ttyS2 ]   || mknod -m 666 /dev/ttyS2 c 4 66
[ -c /dev/ttyFIQ0 ] || mknod -m 666 /dev/ttyFIQ0 c 250 0
[ -c /dev/console ] || mknod -m 600 /dev/console c 5 1
[ -c /dev/null ]    || mknod -m 666 /dev/null c 1 3

hostname bdy-g98
echo "setup hostname: bdy-g98" > /dev/ttyS2

echo "Kdev! Ok! default username:root password:root" > /dev/ttyS2

exec /sbin/init

