#!/bin/sh

/bin/busybox mkdir -p \
        "$ROOT"/bin \
        "$ROOT"/sbin \
        "$ROOT"/usr/bin \
        "$ROOT"/usr/sbin \
        "$ROOT"/proc \
        "$ROOT"/sys \
        "$ROOT"/dev \
        "$sysroot" \
        "$ROOT"/media/cdrom \
        "$ROOT"/media/usb \
        "$ROOT"/tmp \
        "$ROOT"/etc \
        "$ROOT"/run/cryptsetup

# Spread out busybox symlinks and make them available without full path
/bin/busybox --install -s
export PATH="$PATH:/usr/bin:/bin:/usr/sbin:/sbin"

# Make sure /dev/null is a device node. If /dev/null does not exist yet, the command
# mounting the devtmpfs will create it implicitly as an file with the "2>" redirection.
# The -c check is required to deal with initramfs with pre-seeded device nodes without
# error message.
[ -c /dev/null ] || $MOCK mknod -m 666 /dev/null c 1 3

$MOCK mount -t sysfs -o noexec,nosuid,nodev sysfs /sys
$MOCK mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev 2>/dev/null \
        || $MOCK mount -t tmpfs -o exec,nosuid,mode=0755,size=2M tmpfs /dev

# Make sure /dev/kmsg is a device node. Writing to /dev/kmsg allows the use of the
# earlyprintk kernel option to monitor early init progress. As above, the -c check
# prevents an error if the device node has already been seeded.
[ -c /dev/kmsg ] || $MOCK mknod -m 660 /dev/kmsg c 1 11

$MOCK mount -t proc -o noexec,nosuid,nodev proc /proc
# pty device nodes (later system will need it)
[ -c /dev/ptmx ] || $MOCK mknod -m 666 /dev/ptmx c 5 2
[ -d /dev/pts ] || $MOCK mkdir -m 755 /dev/pts
$MOCK mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts

# shared memory area (later system will need it)
mkdir -p "$ROOT"/dev/shm
$MOCK mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm

[ -c /dev/ttyS2 ]   || mknod -m 666 /dev/ttyS2 c 4 66
[ -c /dev/ttyFIQ0 ] || mknod -m 666 /dev/ttyFIQ0 c 250 0
[ -c /dev/console ] || mknod -m 600 /dev/console c 5 1
[ -c /dev/null ]    || mknod -m 666 /dev/null c 1 3

hostname bdy-g98
echo "setup hostname: bdy-g98" > /dev/ttyS2

echo "Kdev! Ok!" > /dev/ttyS2

exec /sbin/init

